
interface _GlobalComponents {
      'LayoutsLayoutFooter': typeof import("../components/Layouts/LayoutFooter.vue")['default']
    'LayoutsLayoutHeader': typeof import("../components/Layouts/LayoutHeader.vue")['default']
    'LayoutsSidebarDark': typeof import("../components/Layouts/Sidebar/Dark.vue")['default']
    'LayoutsSidebarLayoutSidebar': typeof import("../components/Layouts/Sidebar/LayoutSidebar.vue")['default']
    'LayoutsSidebarItem': typeof import("../components/Layouts/Sidebar/SidebarItem.vue")['default']
    'LayoutsVerticalHeader': typeof import("../components/Layouts/VerticalHeader.vue")['default']
    'TaskTableList': typeof import("../components/TaskTableList.vue")['default']
    'TaskTableRow': typeof import("../components/TaskTableRow.vue")['default']
    'CoreSpinner': typeof import("../components/core/Spinner.vue")['default']
    'FormsCreateTask': typeof import("../components/forms/CreateTask.vue")['default']
    'FormsEditTask': typeof import("../components/forms/EditTask.vue")['default']
    'FormsTaskDetails': typeof import("../components/forms/TaskDetails.vue")['default']
    'ModalsReuseableModal': typeof import("../components/modals/ReuseableModal.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyLayoutsLayoutFooter': typeof import("../components/Layouts/LayoutFooter.vue")['default']
    'LazyLayoutsLayoutHeader': typeof import("../components/Layouts/LayoutHeader.vue")['default']
    'LazyLayoutsSidebarDark': typeof import("../components/Layouts/Sidebar/Dark.vue")['default']
    'LazyLayoutsSidebarLayoutSidebar': typeof import("../components/Layouts/Sidebar/LayoutSidebar.vue")['default']
    'LazyLayoutsSidebarItem': typeof import("../components/Layouts/Sidebar/SidebarItem.vue")['default']
    'LazyLayoutsVerticalHeader': typeof import("../components/Layouts/VerticalHeader.vue")['default']
    'LazyTaskTableList': typeof import("../components/TaskTableList.vue")['default']
    'LazyTaskTableRow': typeof import("../components/TaskTableRow.vue")['default']
    'LazyCoreSpinner': typeof import("../components/core/Spinner.vue")['default']
    'LazyFormsCreateTask': typeof import("../components/forms/CreateTask.vue")['default']
    'LazyFormsEditTask': typeof import("../components/forms/EditTask.vue")['default']
    'LazyFormsTaskDetails': typeof import("../components/forms/TaskDetails.vue")['default']
    'LazyModalsReuseableModal': typeof import("../components/modals/ReuseableModal.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const LayoutsLayoutFooter: typeof import("../components/Layouts/LayoutFooter.vue")['default']
export const LayoutsLayoutHeader: typeof import("../components/Layouts/LayoutHeader.vue")['default']
export const LayoutsSidebarDark: typeof import("../components/Layouts/Sidebar/Dark.vue")['default']
export const LayoutsSidebarLayoutSidebar: typeof import("../components/Layouts/Sidebar/LayoutSidebar.vue")['default']
export const LayoutsSidebarItem: typeof import("../components/Layouts/Sidebar/SidebarItem.vue")['default']
export const LayoutsVerticalHeader: typeof import("../components/Layouts/VerticalHeader.vue")['default']
export const TaskTableList: typeof import("../components/TaskTableList.vue")['default']
export const TaskTableRow: typeof import("../components/TaskTableRow.vue")['default']
export const CoreSpinner: typeof import("../components/core/Spinner.vue")['default']
export const FormsCreateTask: typeof import("../components/forms/CreateTask.vue")['default']
export const FormsEditTask: typeof import("../components/forms/EditTask.vue")['default']
export const FormsTaskDetails: typeof import("../components/forms/TaskDetails.vue")['default']
export const ModalsReuseableModal: typeof import("../components/modals/ReuseableModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyLayoutsLayoutFooter: typeof import("../components/Layouts/LayoutFooter.vue")['default']
export const LazyLayoutsLayoutHeader: typeof import("../components/Layouts/LayoutHeader.vue")['default']
export const LazyLayoutsSidebarDark: typeof import("../components/Layouts/Sidebar/Dark.vue")['default']
export const LazyLayoutsSidebarLayoutSidebar: typeof import("../components/Layouts/Sidebar/LayoutSidebar.vue")['default']
export const LazyLayoutsSidebarItem: typeof import("../components/Layouts/Sidebar/SidebarItem.vue")['default']
export const LazyLayoutsVerticalHeader: typeof import("../components/Layouts/VerticalHeader.vue")['default']
export const LazyTaskTableList: typeof import("../components/TaskTableList.vue")['default']
export const LazyTaskTableRow: typeof import("../components/TaskTableRow.vue")['default']
export const LazyCoreSpinner: typeof import("../components/core/Spinner.vue")['default']
export const LazyFormsCreateTask: typeof import("../components/forms/CreateTask.vue")['default']
export const LazyFormsEditTask: typeof import("../components/forms/EditTask.vue")['default']
export const LazyFormsTaskDetails: typeof import("../components/forms/TaskDetails.vue")['default']
export const LazyModalsReuseableModal: typeof import("../components/modals/ReuseableModal.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
